### ISSUE TITLE
민주화 플랫폼의 검색 기능 강화를 위해 데이터를 추가해야 한다고 생각합니다.

### ISSUE THREAD

**Issue by yeji0407** [hamonikr/democratization-expertise#10]
개방형OS 사용자 중심의 전문지식 민주화 플랫폼의 지식검색 기능에 외부 데이터를 추가하면 기능을 강화할 수 있다고 생각합니다.
이를 위해 파이썬 크롤러를 제작하여 국내 개발자 커뮤니티인 hashcode 사이트에서 질문, 답변, 관련 태그 데이터를 수집하고 있습니다.
앞으로 hashcode 외에도 okky, github community, stackoverflow 등의 사이트에서 데이터를 수집할 계획이 있습니다.
이를 진행하는데 있어서 허락을 구합니다. 그리고 현재 수집중인 데이터 외에 더 필요한 데이터를 알려주시면 보완하겠습니다.

**Comment by jullee96** [comment]
참여해주셔서 감사합니다. 추가적으로 궁금한 점이있어서 여쭤봅니다. 
파이썬 크롤러를 이용해 데이터를 수집하였다고 하셨는데 어떤 형식으로 데이터를 저장 중인지 알 수 있을까요?

**Comment by yeji0407** [comment]
우선은 MySQL 을 이용해 내부 DB에 저장중입니다. 사이트 글들의 질문, 답변 등을 text 형식으로 저장했습니다.

**Comment by RyuSeohyeon16** [comment]
아래는 현재 진행중인 파이썬 크롤러의 레포지토리이며
https://github.com/2020-Invesum-Internship/webcrawler-for-hamonikr-demoex

![image](https://user-images.githubusercontent.com/55476465/87634210-cc3ff280-c777-11ea-9675-a0f5be8eb444.png)
현재 Hashcode.co.kr에서 약 8800개의 게시글을 수집하였으며 이를 로컬 MySQL 서버에 위의 데이터베이스 설계방식에 따라 저장하고 있습니다.  필요한 데이터의 양과 이외에도 더 필요하신 정보가 있는지 또한 이후 데이터 전달방식은 어떻게 하는게 편하실지 궁금합니다.

**Comment by jullee96** [comment]
https://github.com/hamonikr/democratization-expertise/tree/master/stacked-q%26a
레파지토리 내부에 stacked-q&a 폴더를 생성했습니다. 해당 폴더에 수집하신 데이터를 .csv 형식으로 올려주시면 내부 db에 반영하도록 
하겠습니다. 감사합니다

**Comment by yeji0407** [comment]
저희가 hahscode.co.kr 외의 다른 사이트에서 크롤링을 시작하려고 합니다.
혹시 아래 사이트 중에서 이미 db를 가지고 계신 사이트가 있나요? 혹시 원하시는 사이트가 있다면 알려주세요!

1.우분투 한국 커뮤니티 (ubuntu-kr.org/#)
2. KLDP

**Comment by jullee96** [comment]
@yeji0407 우분투 한국 커뮤니티에 대한 데이터 수집 부탁드립니다

**Comment by chaeya** [comment]
@yeji0407 @SHRyu416 이 작업의 정리된 내용이 있으면 링크로 공유해주세요~

**Comment by chaeya** [comment]
@all-contributors please add yeji0407 for code

**Comment by chaeya** [comment]
@all-contributors please add SHRyu416 for code
