### ISSUE TITLE
.csv 파일 추가시 빌드 오류 발생에 대해서

### ISSUE THREAD

**Issue by RyuSeohyeon16** [hamonikr/democratization-expertise#18]
https://github.com/hamonikr/democratization-expertise/tree/master/stacked-q%26a
레파지토리 내부에 stacked-q&a 폴더를 생성했습니다. 해당 폴더에 수집하신 데이터를 .csv 형식으로 올려주시면 내부 db에 반영하도록 
하겠습니다. 감사합니다

_Originally posted by @jullee96 in https://github.com/hamonikr/democratization-expertise/issues/10#issuecomment-659796871_

**Comment by RyuSeohyeon16** [comment]
![image](https://user-images.githubusercontent.com/55476465/88006438-953a5a00-cb46-11ea-878c-53513c52ccc7.png)
https://github.com/hamonikr/democratization-expertise/pull/17/checks

만들어주신 레파지토리 내의 stacked-q&a 폴더에 csv 형식 파일을 추가한 뒤 PR을 보냈을 때 빌드에서 Maven 오류가 났었습니다.
일단 전에 보낸 PR은 머지해주셨는데 앞으로도 올릴 때 같은 에러가 발생할 것 같습니다. 
저희가 파일 수정을 통해서 해결해야 하는 부분인지 프로젝트 머지하시는데 영향이 없는 부분인지 알고싶습니다.

**Comment by hamonikr-git** [comment]
@SHRyu416 해당 문제는 현재 처리중에 있으나 maven 프로젝트 빌드 설정 문제로 첨부해주신 데이터와는 별개의 문제로 판단됩니다. 이 부분은 신경쓰시지 않으셔도 됩니다.
