### ISSUE TITLE
**기여자를 위한 문서**

### ISSUE THREAD

**Issue by chaeya** [hamonikr/democratization-expertise#4]
프로젝트 기여자 대상 가이드라인 작성

**Comment by chaeya** [comment]
링크된 현재 작성된 초안을 토대로 위키문서로 보다 친절하게 재 작성이 필요합니다.
https://github.com/hamonikr/democratization-expertise/blob/master/CONTRIBUTING.md

@gon1942 프로젝트 처음 보는 사람이 참여할 수 있도록 리뷰하고 관리해주세요.

**Comment by igothere** [comment]
@chaeya 
https://github.com/hamonikr/democratization-expertise/blob/master/CONTRIBUTING.md 
수정 하였습니다. 확인 부탁드려요~

**Comment by chaeya** [comment]
@bigeden 내용을 일부 수정해서 커밋했습니다
