### ISSUE TITLE
성능테스트를 위한 테스트서버로 배포

### ISSUE THREAD

**Issue by chaeya** [hamonikr/democratization-expertise#54]
- 목표한 성능을 측정하기 위한 테스트 서버가 필요합니다.
@jullee96 개발 결과물이 배포되는 테스트 서버를 준비하고 공유해주세요

**Comment by jullee96** [comment]
- 테스트 서버 : http://dev.hamonikr.org/
- 가용성 테스트 결과 (nGrinder): 10월26일~27일(24H 간 진행)   
![image](https://user-images.githubusercontent.com/66409676/100323825-a7069f00-3009-11eb-8f6a-c974369a0a62.png)
