### ISSUE TITLE
해당 커뮤니티의 주요 사용자를 누구로 생각하시는지가 궁금합니다.

### ISSUE THREAD

**Issue by thinker-94** [hamonikr/democratization-expertise#62]
자유롭게 자신의 의견을 적어주세요.

--
저는 이 커뮤니티가 개방형 os를 사용자가 편하게 이용할 수 있도록 하는게 목적인것으로 생각했습니다.
그런데 크롤링이 개발자의 커뮤니티만 되어있어서 주요 사용자가 개발자인건지 아니면 일반 개방형 os를 사용하는 군 장병, 할머니, 할아버지과 같은 일반 사용자들인지 궁금합니다

**Comment by jullee96** [comment]
먼저 질문해 주셔서 감사합니다.
개발자+개방형 OS에 관심 있는 일반 사용자가 타깃인 범용적인 커뮤니티라고 보시면 됩니다.
주로 사용층이 개발자이다 보니 개방형 OS 관련 질의응답 데이터들이 개발자 커뮤니티에 있어 
크롤링 된 데이터가 그쪽으로 편향되어 보였던 것 같습니다.
현재 크롤링 된 데이터 외에도 일반 사용자들이 질의할만한 데이터도 같이 쌓아두고 있습니다.

**Comment by thinker-94** [comment]
> 먼저 질문해 주셔서 감사합니다.
> 개발자+개방형 OS에 관심 있는 일반 사용자가 타깃인 범용적인 커뮤니티라고 보시면 됩니다.
> 주로 사용층이 개발자이다 보니 개방형 OS 관련 질의응답 데이터들이 개발자 커뮤니티에 있어
> 크롤링 된 데이터가 그쪽으로 편향되어 보였던 것 같습니다.
> 현재 크롤링 된 데이터 외에도 일반 사용자들이 질의할만한 데이터도 같이 쌓아두고 있습니다.

성의있는 답변 감사드립니다.
제가 생각한 이 커뮤니티는 하모니카 os를 쉽게 이용할 수 있도록 사람들이 소통할 수 있는 공간이라고 생각이 듭니다.
하모니카 os도 많은 사용자가 무료로 os를 사용할 수 있도록 하는 철학으로 만든게 아닐까하는 생각을 조심스럽게 해봅니다. 그런데 왜 개발자가 주요 사용층인지 잘 이해가 되지 않네요 

저는 프로젝트가 잘되기 위해서 조금은 비관적으로 생각할 필요가 있다고 생각하는 사람이라서요 ㅜ. 왜냐면 이러한 생각들이 나중에 생길 문제들을 방지할 수 있다고 생각하기 때문입니다. 조금 공격적으로 글이 작성된것처럼 보여질까봐 걱정되어서 덧붙여봤습니다 감사합니다
