### ISSUE TITLE
유저 프로필 소개내용에 첨부된 이미지  리사이징 기능 필요 

### ISSUE THREAD

**Issue by jullee96** [hamonikr/democratization-expertise#66]
**버그 설명**
유저 프로필 소개내용에 첨부된 이미지  리사이징 기능 필요 

**버그 재현 과정**
1. 프로필 수정
2. 이미지 업로드
3. [수정]버튼 클릭

**예상한 결과**
적당한 크기로 리사이징 된 이미지 출력

**Screenshots**
https://lh6.googleusercontent.com/guAR9R4MNIzo1Q3JBd_3tnqMXQhYfC-iFoys1T91w_E8Xa0_cvu9wAO7WXCgkhlu26zUjWiQe4EVxxP1AD7D4JbA0ZPdqB1RHWHcKrT2-5uRw0Bqi8yGCjJ6iJqQxebFBQ0qd9935Q

**자신의 PC 환경**
 - OS: hamoikr3.0
 - Browser : chrome

**Comment by igothere** [comment]
tui editor viewer 옵션 추가로 해결
