### ISSUE TITLE
글 수정시에 원작자에게 [수정]버튼이 없어짐

### ISSUE THREAD

**Issue by jullee96** [hamonikr/democratization-expertise#68]
**버그 설명**
글 수정시에 원작자에게 [수정]버튼이 없어짐 

**버그 재현 과정**
[qna 페이지]
1. 계정 a가 질문 등록(수정 권한 on)
2. 계정 b가 질문 수정
3. 계정 a가 다시 원글을 수정하려고 질문 view페이지에 들어감
4. 계정 a에게 [수정] 버튼이 보이지 않음

**예상한 결과**
계정b가 글을 수정한 뒤에도 계정 a에게 [수정] 버튼 출력

**자신의 PC 환경**
 - OS: hamonikr 3.0 
 - Browser : chrome

**Comment by hamonikr-git** [comment]
https://github.com/hamonikr/democratization-expertise/commit/b189fa0386d8727cf3d1756c7de65b10b3e4a7c5
master에서 수정 사항 반영

**Comment by jullee96** [comment]
https://github.com/hamonikr/democratization-expertise/commit/b189fa0386d8727cf3d1756c7de65b10b3e4a7c5
마스터에 수정사항 반영
