### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by chaeya** [hamonikr/democratization-expertise#75]
@1942kg @jullee96 
저장소 루트에 라이선스 파일이 없습니다. 
아마도 개별 서브 프로젝트를 합치면서 추가하지 않은것 같은데 프로젝트 전체에 적용되도록 LICENSE 파일을 생성해서 머지해주세요.

**Comment by melik210** [comment]
라이센스 루트에 추가하였습니다

**Comment by jullee96** [comment]
라이선스 루트에 추가하였습니다.
